# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-26 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobseeker_name', models.CharField(max_length=200)),
                ('jobseeker_phone', models.CharField(max_length=200)),
                ('jobseeker_email', models.CharField(max_length=200)),
                ('jobseeker_dob', models.DateField(verbose_name='date of birth')),
                ('jobseeker_f_name', models.CharField(max_length=200)),
                ('jobseeker_gender', models.CharField(max_length=200)),
                ('jobseeker_language', models.CharField(max_length=200)),
                ('jobseeker_jobrole', models.CharField(max_length=200)),
                ('jobseeker_experience', models.CharField(max_length=200)),
                ('jobseeker_current_state', models.CharField(max_length=200)),
                ('jobseeker_current_city', models.CharField(max_length=200)),
                ('jobseeker_per_state', models.CharField(max_length=200)),
                ('jobseeker_per_city', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('jobseeker_company_name', models.CharField(max_length=200)),
                ('jobseeker_company_address', models.CharField(max_length=200)),
                ('job_from', models.DateField(verbose_name='from')),
                ('job_to', models.DateField(verbose_name='to')),
                ('job_description', models.CharField(max_length=200)),
                ('jobseeker_handicapped', models.CharField(max_length=200)),
                ('jobseeker_passport', models.CharField(max_length=200)),
                ('jobseeker_education', models.CharField(max_length=200)),
                ('jobseeker_current_salary', models.CharField(max_length=200)),
                ('jobseeker_active', models.CharField(max_length=200)),
                ('joseeker_mitra_id', models.CharField(max_length=200)),
            ],
        ),
    ]
