# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-26 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_category', models.CharField(max_length=200)),
                ('employer_name', models.CharField(max_length=200)),
                ('job_date', models.DateField(verbose_name='job creation_date')),
                ('job_location_city', models.CharField(max_length=200)),
                ('job_location_state', models.CharField(max_length=200)),
                ('job_last_date', models.DateField(verbose_name='last date to apply')),
                ('job_gender', models.CharField(max_length=200)),
                ('job_education', models.CharField(max_length=200)),
                ('job_salary', models.CharField(max_length=200)),
                ('job_skills', models.CharField(max_length=200)),
                ('job_calls', models.IntegerField(max_length=200)),
                ('job_whatsapp', models.IntegerField(max_length=200)),
                ('job_active', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=300)),
            ],
        ),
    ]
