# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-26 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_calls',
            field=models.IntegerField(),
        ),
    ]
