# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-26 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190126_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='jobseeker_password',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
