# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-26 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jobseeker_jobseeker_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_contact',
            field=models.CharField(default=8426020355L, max_length=10),
            preserve_default=False,
        ),
    ]
