# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_job_job_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_english', models.CharField(max_length=200)),
                ('skill_hindi', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='members',
            field=models.ManyToManyField(related_name='job_group', to='app.Skills'),
        ),
    ]
