# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190129_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='jobseeker_creat_date',
            field=models.DateField(default=0, verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
