# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobseeker_create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
