# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobseeker_create_date',
        ),
    ]
