# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_job_jobseeker_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='registration_date',
        ),
    ]
