# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_college_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='about',
            field=models.CharField(default='dfghjk', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.CharField(default='dfghjkl', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='contact_person',
            field=models.CharField(default='asdfghjk', max_length=100),
            preserve_default=False,
        ),
    ]
