# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190203_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=10)),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='College_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_venue', models.CharField(max_length=100)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_description', models.CharField(max_length=500)),
            ],
        ),
    ]
