# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_college_details_college_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_event',
            name='event_phone',
            field=models.CharField(default='eghjk', max_length=20),
            preserve_default=False,
        ),
    ]
