# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_college_event_event_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=10)),
                ('contact_person', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('comapny_address', models.CharField(max_length=100)),
                ('company_acc_creation', models.DateField(verbose_name='account creation on')),
            ],
        ),
    ]
