# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_password',
            field=models.CharField(default='123456789', max_length=100),
            preserve_default=False,
        ),
    ]
